# Generated by Django 4.2.7 on 2023-12-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('total_registered_users', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sold_products', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Website Stats',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
